#!/usr/bin/env python

import sys
import uuid
import socket

from datetime import datetime
from email.parser import Parser

from pymongo import Connection

ALPHABET = "ZU1eOAjR3bpzFtGXYaSN82rlLQMV7D6uwiPIochd5sf4H9xkCEBnTKmqyWv0gJ"

def base62_encode(num, alphabet=ALPHABET):
    """Encode a number in Base X

    `num`: The number to encode
    `alphabet`: The alphabet to use for encoding
    """
    if (num == 0):
        return alphabet[0]
    arr = []
    base = len(alphabet)
    while num:
        rem = num % base
        num = num // base
        arr.append(alphabet[rem])
    arr.reverse()
    return ''.join(arr)

parser = Parser()
msg = parser.parse(sys.stdin)

conn = Connection()

sdb = conn.situationdb
situations = sdb.situations
if sys.argv[1]:
	uuid_int = uuid.UUID(sys.argv[1]).int
else:
	uuid_int = uuid.uuid4().int

if sys.argv[2]:
	attachment_dir = sys.argv[2]
else:
	attachment_dir = "undefined"

situation_id_short = base62_encode(uuid_int)
situations.insert({'situation_id': situation_id_short,
		'situation': msg['SUBJECT'],
		'owner': msg['FROM'],
		'participants': msg['CC'],
		'opened': datetime.utcnow(),
		'ingress_host': socket.gethostname(),
		'attachment_directory': attachment_dir,
		'notification': {'email': "status+%s@tactical.io" % (situation_id_short), 
				'irc': '%s' % (situation_id_short) },
		'ingress':msg['TO']})

